"""Sample script to batch update Feishu docx content."""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parents[3]
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from move37.utils.feishu import FeishuClient


def build_simple_children(content: str) -> list[dict]:
    """Build simple children blocks for descendant create API."""
    return [
        {
            "block_type": 3,
            "heading1": {
                "elements": [
                    {
                        "text_run": {
                            "content": "Move37 Auto Write",
                        }
                    }
                ]
            },
        },
        {
            "block_type": 2,
            "paragraph": {
                "elements": [
                    {
                        "text_run": {
                            "content": content,
                        }
                    }
                ]
            },
        },
        {
            "block_type": 5,
            "quote": {
                "elements": [
                    {
                        "text_run": {
                            "content": "Generated by Feishu OpenAPI",
                        }
                    }
                ]
            },
        }
    ]


def main() -> None:
    """Read .env and write simple content into a target docx document."""
    load_dotenv(PROJECT_ROOT / ".env")

    parser = argparse.ArgumentParser(description="Write content blocks to a Feishu docx document.")
    parser.add_argument("--document-id", required=True, help="Target docx document id.")
    parser.add_argument(
        "--block-id",
        required=True,
        help="Target parent block id (for example, root block id).",
    )
    parser.add_argument(
        "--content",
        default="Move37 write_docx_content sample\n\nThis content is created by API.",
        help="Plain text content to insert.",
    )
    args = parser.parse_args()

    app_id = str(os.getenv("FEISHU_APP_ID", "")).strip()
    app_secret = str(os.getenv("FEISHU_APP_SECRET", "")).strip()

    client = FeishuClient(app_id=app_id, app_secret=app_secret)
    children_payload = build_simple_children(args.content)
    result = client.write_docx_content(
        document_id=args.document_id,
        block_id=args.block_id,
        children=children_payload,
    )
    print(json.dumps(result, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
